#!/bin/bash

confdir=$HOME/.ssh
confsubdir=$confdir/config.d
config=$confdir/config

[ -d $confsubdir ] || mkdir -p $confsubdir

# ZDOTDIR should always be set
source "$ZDOTDIR/lib/libhooks.sh"

rebuild_config "$config" "${confsubdir#$HOME/}"

chmod go-rwx -R $config $confdir $confsubdir
