#!/bin/bash

confdir=$HOME/.ssh
confsubdir=$confdir/config.d
subconf=default
if test -d "${confsubdir}/$(hostname)"; then
    subconf=$(hostname)
fi
config=$confdir/config

[ -d $confsubdir ] || mkdir -p $confsubdir

# ZDOTDIR should always be set
source "$ZDOTDIR/lib/libhooks.sh"

echo "Using config directory : ${confsubdir#$HOME/}/${subconf}"
rebuild_config "$config" "${confsubdir#$HOME/}/${subconf}"

chmod go-rwx -R $config $confdir $confsubdir
